<?php

/**
 * @file
 * Primary module hooks for openideal_faq module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_multiple_field_remove_button_field_types_alter().
 */
function openideal_faq_multiple_field_remove_button_field_types_alter(array &$fieldTypes) {
  $fieldTypes[] = 'faqfield';
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function openideal_faq_field_widget_faqfield_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['answer']['#allowed_formats'] = ['full_html'];
  $element['#after_build'][] = '_remove_textarea_help';
}

/**
 * The #after_build callback for text widgets.
 */
function _remove_textarea_help($form_element, FormStateInterface $form_state) {
  if (isset($form_element['answer']['format'])) {
    unset($form_element['answer']['format']['help']);
    unset($form_element['answer']['format']['guidelines']);
    unset($form_element['answer']['format']['#type']);
    unset($form_element['answer']['format']['#theme_wrappers']);
  }
  return $form_element;
}
