<?php

/**
 * @file
 * Contains install and update functions for openideal_flavour.
 */

/**
 * Implements hook_install().
 */
function openideal_flavour_install() {
  node_access_needs_rebuild(TRUE);
}

/**
 * Implements hook_uninstall().
 */
function openideal_flavour_uninstall() {
  node_access_needs_rebuild(TRUE);
}

/**
 * Implements hook_update_N().
 */
function openideal_flavour_update_8001() {
  node_access_needs_rebuild(TRUE);
}
