<?php

/**
 * @file
 * Contains openideal_idea.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatch;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\flag\FlagInterface;
use Drupal\group\Entity\GroupContent;
use Drupal\node\NodeInterface;
use Drupal\openideal_user\Event\OpenidealUserEvents;
use Drupal\openideal_user\Event\OpenidealUserGroupEvent;
use Drupal\openideal_user\Event\OpenidealUserJoinedSiteEvent;
use Drupal\openideal_user\Form\OpenidealSecondStepRegistrationForm;
use Drupal\transaction\TransactionInterface;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openideal_user_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\social_api\Plugin\NetworkManager $network_manager */
  $network_manager = \Drupal::service('plugin.network.manager');
  $social_plugins = \Drupal::config('social_auth.settings')->get('auth');

  // Remove socials that aren't configured properly.
  foreach ($social_plugins as $plugin_id => $data) {
    if (!$network_manager->createInstance($plugin_id)->getSdk()) {
      unset($social_plugins[$plugin_id]);
    }
  }
  $form['actions']['social_buttons'] = [
    '#theme' => 'login_with',
    '#social_networks' => $social_plugins,
    '#weight' => '1',
  ];
}

/**
 * Implements hook_user_login().
 */
function openideal_user_user_login(UserInterface $account) {
  if (RouteMatch::createFromRequest(\Drupal::request())->getRouteName() == 'user_registrationpassword.confirm') {
    $event = new OpenidealUserJoinedSiteEvent($account);
    \Drupal::service('event_dispatcher')->dispatch(OpenidealUserEvents::OPENIDEA_USER_JOINED_THE_SITE, $event);

    // Redirect user if joined the site for the first
    // time via the user_registrationpassword one time link.
    $response = new RedirectResponse(URL::fromRoute('openideal_user.register.user.more_about_you')->toString());
    $response->send();
  }

  // If user was created by UI or via social logins then dispatch
  // OpenidealUserEvents.
  if (!$account->getLastAccessedTime()) {
    $event = new OpenidealUserJoinedSiteEvent($account);
    \Drupal::service('event_dispatcher')->dispatch(OpenidealUserEvents::OPENIDEA_USER_JOINED_THE_SITE, $event);
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function openideal_user_entity_type_alter(array &$entity_types) {
  $entity_types['user']
    ->setFormClass('additional_details', OpenidealSecondStepRegistrationForm::class);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function openideal_user_preprocess_page(&$variables) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    $user_id = \Drupal::currentUser()->id();
    $user = \Drupal::entityTypeManager()->getStorage('user')->load($user_id);
    $current_route = \Drupal::service('current_route_match')->getRouteName();
    // Check if any of user field empty, if so set a remind message.
    if (($user->get('field_age_group')->isEmpty() || $user->get('field_gender')->isEmpty())
      && ($current_route !== 'entity.user.edit_form' && $current_route !== 'openideal_user.register.user.more_about_you')
      && !$user->hasRole('administrator')) {
      \Drupal::messenger()->addMessage(t('Please fill your <a href="@link">profile</a>',
        ['@link' => Url::fromRoute('entity.user.edit_form', ['user' => $user_id])->toString()]
      ));
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function openideal_user_group_content_insert(GroupContent $entity) {
  if ($entity->getGroupContentType()->id() == 'idea-group_membership') {
    $event = new OpenidealUserGroupEvent($entity);
    \Drupal::service('event_dispatcher')->dispatch(OpenidealUserEvents::OPENIDEA_USER_JOINED_GROUP, $event);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function openideal_user_group_content_delete(GroupContent $entity) {
  if ($entity->getGroupContentType()->id() == 'idea-group_membership') {
    $event = new OpenidealUserGroupEvent($entity);
    \Drupal::service('event_dispatcher')->dispatch(OpenidealUserEvents::OPENIDEA_USER_LEFT_GROUP, $event);
  }
}

/**
 * Implements hook_flag_action_access().
 *
 * If user is Idea creator then restrict "unfollow" access.
 */
function openideal_user_flag_action_access($action, FlagInterface $flag, AccountInterface $account, EntityInterface $flaggable = NULL) {
  if ($flaggable
    && $flaggable instanceof NodeInterface
    && $action == 'unflag'
    && $flaggable->bundle() == 'idea'
    && $flaggable->uid->target_id == $account->id()) {
    return AccessResult::forbidden();
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function openideal_user_transaction_insert(TransactionInterface $entity) {
  // If transaction was added manually then execute it immediately.
  if ($entity->isPending()) {
    $entity->execute();
  }
}
