<?php

/**
 * @file
 * Contains openideal_content.module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_link_alter().
 */
function openideal_content_link_alter(&$variables) {
  // All external links should open in a new tab.
  if ($variables['url']->isExternal()) {
    $variables['options']['attributes']['target'] = '_blank';
  }
}

/**
 * Implements hook_views_query_alter().
 */
function openideal_content_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'public_activity' && $view->current_display === 'personalized_activity_block' && $user = \Drupal::routeMatch()->getParameter('user')) {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['value'] == '[user-page-id]') {
          $condition['value'] = $user->id();
        }
      }
    }
  }
}
